### ISSUE TITLE
Request for assistance

### ISSUE THREAD

**Issue by garth-waters** [timmaffett/custom_mouse_cursor#1]
Thanks very much for this package

It seems that the hotX and hotY do not work when creating an asset from a PNG image. Is this correct or is there a way around this?

Many Thanks
Garth Waters

**Comment by timmaffett** [comment]
I was not aware of a problem with hotX,Y and PNG images.   Could you provide more details about the platform, etc and how/why you are seeing this ?

**Comment by timmaffett** [comment]
The example for the web platform at
https://timmaffett.github.io/custom_mouse_cursor/#/

has a variety of different PNG w/HotX/Y settings examples.  Click on any colored row and then you can test the cursor at the bottom of the page, long with the hotspot.   (You can see where the line draws from the hotspot)
This is the example from the package source.
(The orange row and the blue rows use PNG files and non 0,0 hotspots)

**Comment by garth-waters** [comment]
Thanks for the response.
I solved it by creating an svg file and used the icon feature to create the mouse cursor

**Comment by timmaffett** [comment]
Thats good Garth, can I ask what platform you were using when you saw the PNG problem ?
I would still like to fix the bug...

**Comment by timmaffett** [comment]
@garth-waters  I am going to close this issue as there is nothing else I can do without the PNG file in question,
